### ISSUE TITLE
Set up .env file

### ISSUE THREAD

**Issue by lawsonbh** [lawsonbh/character-generator#10]
I want to stop setting my command line env vars every time I launch the app :frowning:

**Comment by bbelderbos** [comment]
haha yep :)

- How to handle environment variables in Python -> https://pybit.es/articles/how-to-handle-environment-variables-in-python/
- Or video: How to manage environment variables in Django with python-decouple - https://www.youtube.com/watch?v=LkyhTqDrSxA

**Comment by lawsonbh** [comment]
Resolved by #14
