### ISSUE TITLE
Is the db under version control perhaps?

### ISSUE THREAD

**Issue by bbelderbos** [lawsonbh/character-generator#12]
Pulling in the changes I saw this:

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/387927/191983169-e9d43a7c-4b8e-41e6-93e2-2f5485014ad5.png">

**Comment by bbelderbos** [comment]
Fixed this here: https://github.com/lawsonbh/character-generator/pull/13

**Comment by lawsonbh** [comment]
Closed by #13
