### ISSUE TITLE
Revise messy navigation experience

### ISSUE THREAD

**Issue by lawsonbh** [lawsonbh/character-generator#17]
Right now I am not really leveraging the home page. 

We do have good redirects but I'd like to tie these together into a good navigation space. Will look at revising the home url for the bodybank set of urls and the index url under the character_generator set of urls.

Goal is to set this up going into creating a more wizard like experience :mage:

**Comment by bbelderbos** [comment]
We can think more about the wizard experience / design, once we have the ego -> morph assignment step coded right?

**Comment by lawsonbh** [comment]
#22 helped this issue
