### ISSUE TITLE
Set up models for character generation

### ISSUE THREAD

**Issue by lawsonbh** [lawsonbh/character-generator#2]
We have the following:
- User
- Ego
- Morph
- Item

Still thinking through how to incorporate things like background and profession into the MVP. Right now - we can deliver value and get it into users hands with the four concepts above but pretty soon after that we will want to make sure we can change character sheet values appropriately when one background is selected as opposed to another.

Concepts like this that may be tricky without building additional models:
- Background
- Interest
- Career
- Faction

**Comment by bbelderbos** [comment]
User comes with Django, no need to define. Let's focus on Ego - Morph - Item first.

**Comment by lawsonbh** [comment]
- [x] Ego
- [x] Morph
- [x] Item

**Comment by lawsonbh** [comment]
Item is the last one on the list for the longest outstanding issue :smiling_imp:

**Comment by bbelderbos** [comment]
haha nws, but yeah we do need those right? :)

**Comment by lawsonbh** [comment]
Closed by #43
